# Generated by Django 4.1.7 on 2023-02-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=120)),
                ('complaint_desc', models.TextField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category_model')),
            ],
        ),
    ]
