# Generated by Django 4.1.7 on 2023-02-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_model_lvl1_title_category_model_lvl2_title'),
        ('complaint', '0002_complain_model_created_at_complain_model_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complain_model',
            new_name='complaint_model',
        ),
    ]
