# Generated by Django 4.1.7 on 2023-02-21 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_model_cat_name_category_model_dept_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category_model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
